# Truster <https://truster.dev>
# Copyright The Truster Authors
# SPDX-License-Identifier: Apache-2.0

FROM gcr.io/distroless/static-debian12:nonroot@sha256:f5b485ea962d9bd1186b2f6b3a061191539b905b82ec395de78cbfae51f20e35

ARG TARGETOS
ARG TARGETARCH
ARG VERSION=dev
ARG BUILD_DATE=unknown
ARG COMMIT_HASH=unknown

LABEL org.opencontainers.image.title="Truster" \
      org.opencontainers.image.description="A minimal self-hosted OIDC issuer for your apps and Kubernetes clusters" \
      org.opencontainers.image.source="https://github.com/truster-dev/truster" \
      org.opencontainers.image.documentation="https://truster.dev/docs/" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.revision="${COMMIT_HASH}"

COPY --chmod=555 bin/${TARGETOS}_${TARGETARCH}/truster /truster

ENTRYPOINT ["/truster"]
CMD ["serve", "--config", "/etc/truster/config.jsonc"]
