# Easy OIDC <https://easy-oidc.dev>
# Copyright The Easy OIDC Authors
# SPDX-License-Identifier: Apache-2.0

issuer: http://127.0.0.1:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

telemetry:
  http: 0.0.0.0:5558

oauth2:
  skipApprovalScreen: true
  passwordConnector: local

staticClients:
# Easy OIDC uses this client to delegate interactive user login to Dex.
- id: easy-oidc-interactive-e2e
  secret: easy-oidc-interactive-e2e-secret
  redirectURIs:
  - 'http://127.0.0.1:8080/callback/generic'
  name: 'Easy OIDC Interactive E2E'
# The E2E script uses this client to obtain the external token that Easy OIDC exchanges.
- id: ci-token-exchange-e2e
  secret: ci-token-exchange-e2e-secret
  name: 'CI Token Exchange E2E'

connectors:
- type: mockCallback
  id: mock
  name: Mock

enablePasswordDB: true

staticPasswords:
- email: "test@example.com"
  hash: "$2a$10$2cEClpIvheg2vsGwgU0asON7mHsxVRQoPOYmwn9HcPI8mkhy4F14e"
  username: "test"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
