# Easy OIDC <https://easy-oidc.dev>
# Copyright The Easy OIDC Authors
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: easy-oidc

before:
  hooks:
    - make precommit

builds:
  - id: easy-oidc
    main: ./cmd/easy-oidc
    binary: easy-oidc
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc-13
    ldflags:
      - -s -w
      - -X github.com/easy-oidc/easy-oidc/internal/buildvars.buildVersion={{ .Tag }}
      - -X github.com/easy-oidc/easy-oidc/internal/buildvars.buildDate={{ .Date }}
      - -X github.com/easy-oidc/easy-oidc/internal/buildvars.commitHash={{ .FullCommit }}
      - -X github.com/easy-oidc/easy-oidc/internal/buildvars.commitDate={{ .Env.COMMIT_DATE }}
      - -X github.com/easy-oidc/easy-oidc/internal/buildvars.commitBranch=unknown
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: easy-oidc
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - examples/**/*

signs:
  - artifacts: checksum
    cmd: cosign
    signature: "${artifact}.bundle"
    args: ["sign-blob", "--yes", "--bundle=${signature}", "${artifact}"]
    output: true

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha512

sboms:
  - id: archive
    artifacts: archive
    documents:
      - "{{ .ArtifactName }}.spdx.json"
  - id: binary
    artifacts: binary
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_{{ .Binary }}.spdx.json"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: easy-oidc
    name: easy-oidc
  draft: true
  prerelease: auto
  replace_existing_artifacts: false
