# Truster <https://truster.dev>
# Copyright The Truster Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: truster
description: A minimal, production-ready deployment of Truster
type: application
version: 0.1.0
appVersion: "2.0.0"
kubeVersion: ">=1.24.0-0"
home: https://truster.dev
sources:
  - https://github.com/truster-dev/truster
